version: '3.9'
services:
    backend:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
          - 8088:5000
        volumes:
            - .:/app
        depends_on:
            - db
    
    db:
        image: mysql:latest
        restart: always
        environment:
            MYSQL_DATABASE: main
            MYSQL_USER: de
            MYSQL_PASSWORD: root
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - .dbdata:/var/lib/mysql
        ports:
            - 33067:3306