version: '1.1'
services:
    app:
      build:
        context: .
        dockerfile: Dockerfile
      ports:
        - "80:80"
      links:
        - db
      depends_on:
        - db

    db:
      image: mysql:latest
      restart: unless-stopped
      environment:
        MYSQL_DATABASE: dashmote
        MYSQL_USER: ${USER}
        MYSQL_PASSWORD: ${PASSWORD}
        MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
      ports:
        - "3307:3306"
      volumes:
        - type: volume
          source: mysql-data
          target: /var/lib/mysql

volumes:
  mysql-data:
    external: false
